version: '3.8'

services:
  
  backend:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: "backend"
    restart: unless-stopped
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cec
    ports:
      - "5432:5432"
    volumes:
      - ./backup/pg-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_DATABASE: cec
    ports:
      - "27017:27017"
    volumes:
      - ./backup/mongo-data:/data/db
      - ./backup/mongo-config:/data/configdb