version: '3.8'

services:

  backend:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: "backend"
    ports:
      - "3000:3000"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_HOST=0.0.0.0
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cec
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_TIMEZONE=Asia/Tehran
      - MONGODB_URI="mongodb://mongo/?readPreference=primary&ssl=false&directConnection=true"
    depends_on:
      - postgres
      # - mongo

  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cec
    ports:
      - "5432:5432"
    volumes:
      - ./backup/pg-data:/var/lib/postgresql/data

  mongo:
    container_name: "mongo"
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./backup/mongo-data:/data/db
      - ./backup/mongo-config:/data/configdb
